# Generated by Django 5.0.3 on 2024-03-22 19:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GymClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(choices=[('Yoga', 'Yoga'), ('Zumba', 'Zumba'), ('Pilates', 'Pilates'), ('Spin', 'Spin')], max_length=50)),
                ('instructor', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('day', models.CharField(choices=[('Monday', 'Monday'), ('Tuesday', 'Tuesday'), ('Wednesday', 'Wednesday'), ('Thursday', 'Thursday'), ('Friday', 'Friday'), ('Saturday', 'Saturday'), ('Sunday', 'Sunday')], max_length=20)),
                ('time', models.TimeField()),
                ('capacity', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], max_length=20)),
            ],
        ),
        migrations.RemoveField(
            model_name='livestreamsessionstable',
            name='class_id',
        ),
        migrations.AlterField(
            model_name='scheduletable',
            name='class_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.gymclass'),
        ),
        migrations.DeleteModel(
            name='ClassesTable',
        ),
    ]
