# Generated by Django 5.0.3 on 2024-03-22 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_appointment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointment',
            name='date',
        ),
        migrations.AddField(
            model_name='appointment',
            name='day',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
